#!/usr/bin/env bash
set -eu

network=$1
user=$2
workspace=$3

docker_opts=( --rm --init --read-only --cap-drop ALL --security-opt "no-new-privileges=true" )

if [ -t 0 ] && [ -t 1 ]; then
  docker_opts+=( -it )
fi

docker run "${docker_opts[@]}" \
  --network="${network}" \
  --workdir "/home/${user}/workspace/$(realpath --relative-to="${workspace}" "$(pwd)")" \
  --mount type=bind,src=$(realpath "${workspace}"),dst="/home/${user}/workspace" \
  "${@:4}"